
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    # Raise pull requests for version updates
    # to pip against the `develop` branch
    target-branch: "update_rails_6_0"
    # Labels on pull requests for version updates only
    labels:
      - "bundle dependencies"
