# require: rubocop-performance

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Max: 35

AllCops:
  Exclude:
    - db/migrate/*.rb
    - db/schema.rb
    - db/seeds.rb
    - db/structure.sql
    - bin/*
    - script/*
    - config/routes.rb
    - spec/rails_helper.rb
    - spec/factories/*

Style/Lambda:
  Enabled: false

Style/UnneededInterpolation:
  Enabled: false

Layout/IndentFirstArgument:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Security/JSONLoad:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals
