default: &default
  adapter: postgresql
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test
