#
# This file configures the New Relic Agent.  New Relic monitors Ruby, Java,
# .NET, PHP, Python and Node applications with deep visibility and low
# overhead.  For more information, visit www.newrelic.com.
#
# Generated August 15, 2016
#
# This configuration file is custom generated for app35759379@heroku.com
#
# For full documentation of agent configuration options, please refer to
# https://docs.newrelic.com/docs/agents/ruby-agent/installation-configuration/ruby-agent-configuration

development:
  # Required license key associated with your New Relic account.
  license_key: ENV['NEW_RELIC_LICENSE_KEY'] || ENV['NEW_RELIC_API_KEY']

  # Your application name. Renaming here affects where data displays in New
  # Relic. For more details, see https://docs.newrelic.com/docs/apm/new-relic-apm/maintenance/renaming-applications
  app_name: EBWiki (Development)

  # NOTE: There is substantial overhead when running in developer mode.
  # Do not use for production or load testing.
  developer_mode: true

  # Logging level for log/newrelic_agent.log
  log_level: info

test:
  # It doesn't make sense to report to New Relic from automated test runs.
  license_key: ENV['NEW_RELIC_LICENSE_KEY'] || ENV['NEW_RELIC_API_KEY']
  monitor_mode: false
  log_level: info

staging:
  license_key: ENV['NEW_RELIC_LICENSE_KEY'] || ENV['NEW_RELIC_API_KEY']
  app_name: EBWiki (Staging)
  log_level: info

production:
  license_key: ENV['NEW_RELIC_LICENSE_KEY'] || ENV['NEW_RELIC_API_KEY']
  app_name: EBWiki
  log_level: info
