#
# This file configures the New Relic Agent.  New Relic monitors Ruby, Java,
# .NET, PHP, Python and Node applications with deep visibility and low
# overhead.  For more information, visit www.newrelic.com.
#
# Generated August 15, 2016
#
# This configuration file is custom generated for app35759379@heroku.com
#
# For full documentation of agent configuration options, please refer to
# https://docs.newrelic.com/docs/agents/ruby-agent/installation-configuration/ruby-agent-configuration

# Environment-specific settings are in this section.
# RAILS_ENV or RACK_ENV (as appropriate) is used to determine the environment.
# If your application has other named environments, configure them here.
development:
  license_key: ENV['NEW_RELIC_LICENSE_KEY']
  app_name: EBWiki (Development)
  log_level: info
  developer_mode: true

test:
  license_key: ENV['NEW_RELIC_LICENSE_KEY']
  app_name: EBWiki
  log_level: info
  monitor_mode: false

staging:
  license_key: ENV['NEW_RELIC_LICENSE_KEY']
  app_name: EBWiki (Staging)
  log_level: info

production:
  license_key: ENV['NEW_RELIC_LICENSE_KEY']
  app_name: EBWiki
  log_level: info
