default: &default
  url: redis://localhost:6379/0
  pool_size: 5
  timeout: 5

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  url: <%= ENV['REDIS_URL'] %>
  pool_size: <%= ENV.fetch("REDIS_POOL_SIZE", 10) %>
  timeout: <%= ENV.fetch("REDIS_TIMEOUT", 5) %>
