-- Tables Hanami reads from the existing Rails/Postgres schema.
-- This is a production-shaped subset of db/structure.sql for local and CI
-- test databases. Production and development should keep using the Rails
-- structure; do not run Hanami migrations against the shared database.

CREATE TYPE public.cause_of_death AS ENUM (
    'choking',
    'shooting',
    'beating',
    'taser',
    'vehicular',
    'medical neglect',
    'response to medical emergency',
    'suicide',
    'chemical_agents_or_weapons',
    'drowning',
    'stabbing',
    'bombing'
);

CREATE TYPE public.jurisdiction AS ENUM (
    'unknown',
    'local',
    'state',
    'federal',
    'university',
    'commercial'
);

CREATE TABLE public.states (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name character varying,
    iso character varying,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    ansi_code character varying,
    slug character varying
);

CREATE TABLE public.cases (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title character varying NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    date date,
    state_id integer REFERENCES public.states(id),
    city character varying NOT NULL,
    address character varying,
    zipcode character varying,
    longitude double precision,
    latitude double precision,
    avatar character varying,
    slug character varying,
    video_url character varying,
    state character varying,
    age integer,
    overview text NOT NULL,
    community_action text,
    litigation text,
    country character varying,
    remove_avatar boolean,
    summary text NOT NULL,
    follows_count integer DEFAULT 0 NOT NULL,
    default_avatar_url character varying,
    blurb text,
    cause_of_death public.cause_of_death,
    tsv tsvector GENERATED ALWAYS AS (
      to_tsvector(
        'english'::regconfig,
        (
          (COALESCE(title, ''::character varying))::text || ' ' ||
          COALESCE(blurb, ''::text) || ' ' ||
          COALESCE(overview, ''::text) || ' ' ||
          (COALESCE(city, ''::character varying))::text || ' ' ||
          COALESCE(summary, ''::text)
        )
      )
    ) STORED
);

CREATE UNIQUE INDEX index_cases_on_slug ON public.cases (slug);
CREATE INDEX index_cases_on_tsv ON public.cases USING gin (tsv);

CREATE TABLE public.subjects (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name character varying NOT NULL,
    age integer,
    gender_id integer,
    ethnicity_id integer,
    unarmed boolean,
    mentally_ill boolean,
    veteran boolean,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    case_id integer REFERENCES public.cases(id) ON DELETE CASCADE,
    homeless boolean
);

CREATE TABLE public.agencies (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name character varying NOT NULL,
    street_address character varying,
    city character varying,
    state_id integer REFERENCES public.states(id),
    zipcode character varying,
    telephone character varying,
    email character varying,
    website character varying,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    slug character varying,
    longitude double precision,
    latitude double precision,
    jurisdiction public.jurisdiction DEFAULT 'unknown'::public.jurisdiction
);

CREATE TABLE public.case_agencies (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    case_id integer REFERENCES public.cases(id) ON DELETE CASCADE,
    agency_id integer REFERENCES public.agencies(id) ON DELETE CASCADE,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);

CREATE TABLE public.links (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    url character varying,
    linkable_id integer,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    title character varying,
    linkable_type character varying
);

CREATE TABLE public.users (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email character varying DEFAULT ''::character varying NOT NULL,
    encrypted_password character varying DEFAULT ''::character varying NOT NULL,
    reset_password_token character varying,
    reset_password_sent_at timestamp without time zone,
    remember_created_at timestamp without time zone,
    sign_in_count integer DEFAULT 0 NOT NULL,
    current_sign_in_at timestamp without time zone,
    last_sign_in_at timestamp without time zone,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    admin boolean DEFAULT false,
    name character varying NOT NULL,
    description text,
    slug character varying,
    analyst boolean DEFAULT false,
    confirmation_token character varying,
    confirmed_at timestamp without time zone,
    confirmation_sent_at timestamp without time zone
);

CREATE TABLE public.comments (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    content text,
    commentable_id integer,
    commentable_type character varying,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    user_id integer
);

CREATE TABLE public.follows (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    followable_id integer NOT NULL,
    followable_type character varying NOT NULL,
    follower_id integer NOT NULL,
    follower_type character varying NOT NULL,
    blocked boolean DEFAULT false NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);

CREATE TABLE public.organizations (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name character varying,
    description text,
    website character varying,
    telephone character varying,
    avatar character varying,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);

CREATE TABLE public.versions (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    item_type character varying NOT NULL,
    item_id integer NOT NULL,
    event character varying NOT NULL,
    whodunnit character varying,
    object text,
    created_at timestamp without time zone,
    object_changes text,
    ip character varying,
    transaction_id integer,
    comment text DEFAULT ''::text,
    author_id integer
);
