---
name: Publish Docker Image

on:
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  publish_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.5.0
      - name: Login to DockerHub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6.5.0
        with:
          push: true
          tags: |
            ebwiki/ebwiki:latest
            ebwiki/ebwiki:${{ github.run_number }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
